### ISSUE TITLE
Is it possible to use reductor without android?

### ISSUE THREAD

**Issue by se-panfilov** [Yarikx/reductor#21]
Hey, thanks for reductor.
It's not an issue, but a question. And yeah, I'm not really good at java.

I have two questions:

1. Is it possible (a good idea?) to use reductor on pure java app (not android)?

2. Some parts of example confusing me. Like this one:

```Java
 public static CounterReducer create() {
        return new CounterReducerImpl(); //Note: usage of generated class
    }
```

Is that an android magic?

**Comment by Yarikx** [comment]
Hi se-panfilov,

1. Yes! Reductor does not depend on android or any other dependency.
Therefore you can use it in pure Java app. The only thing that might be
different is how you add annotation processing to your build config.
Is it a good idea or not depends of type and architecture of your app.

2. That's not a magic, but annotation processor who knows how to generate
CounterReducerImpl.

Reductor contains two parts: Library and annotation processor. The latter
is responsible for this kind of magic

On Fri, 24 Mar 2017, 07:24 Sergey Panfilov, <notifications@github.com>
wrote:

Hey, thanks for reductor.

I have two questions:

   1.

   Is it possible (a good idea?) to use reductor on pure java app (not
   android)?
   2.

   Some parts of example confusing me. Like this one:

 public static CounterReducer create() {
        return new CounterReducerImpl(); //Note: usage of generated class
    }

Is that an android magic?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Yarikx/reductor/issues/21>, or mute the thread

**Comment by se-panfilov** [comment]
@Yarikx Thanks for answers.

I'll close issue, but tbh It would be good to have an example with setup for non-android environment. Cause me and perhaps someone other guys may feel troubles with that.
